# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 1463d990e0801964764a375260dca598513f3be5 # frozen: v3.3.3
    hooks:
      - id: prettier
        files: \.(md|rst|toml|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 8b76f04e7e5a9cd259e9d1db7799599355f97cdf # frozen: v0.8.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
