[build-system]
requires = [
  "setuptools",
  "cython<3",
  # Newer than NEP29-minimum: compile against oldest numpy available
  "numpy>=1.25; python_version > '3.8'",
  # NEP29-minimum as of Sep 21, 2023
  "numpy==1.22; python_version >= '3.7' and python_version < '3.9'",
]
build-backend = "setuptools.build_meta"
