name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        python_version: ["3.9"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
      - name: Install
        run: |
          pip install nose3 coverage
          pip install .
      - name: Show environment
        run: env
      - name: Library tests
        run: |
          mkdir ../tmp
          cd ../tmp
          python ../nipy/tools/nipnost --traverse-namespace --verbosity=3 \
            --with-coverage --cover-xml-file=../nipy/coverage.xml --cover-config-file=../nipy/.coveragerc \
            nipy
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
